[entryPoints]
    [entryPoints.http]
        address = ":80"

    [entryPoints.https]
        address = ":443"

    [http]
        [http.routers]
            [http.routers.https]
                entrypoints = ["http"]
                middlewares = ["redirect"]
                rule = "HostRegexp(`{host:.+}`)"
                service = "api@internal"

        [http.middlewares]
            [http.middlewares.redirect.redirectScheme]
                scheme = "https"
                permanent = true

        [http.middlewares.adminAuth.basicAuth]
            # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
            users = [
                "admin:$$apr1$$oLh2Faj8$$/iDVbVbJiNH.r0IqkP0KC."
            ]

    [api]
        dashboard = true
        insecure = false

    [log]
        level = "DEBUG"
        format = "json"

    [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
        entryPoint = "metrics"
