apiVersion: v1
kind: Secret
metadata:
  name: git-secret
type: Opaque
data:
  # Generate a personal access token from GitHub
  # See https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
  personalAccessToken: {% GITHUB_ACCESS_TOKEN %}
  # The secret specified when creating the webhook on GitHub
  # This is used to validate incoming webhook messages.
  webhookSecret: {% GITHUB_WEBHOOK_SECRET %}
