apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: go-app
spec:
  serviceAccount: docker-bot
  pipelineRef:
    name: pipeline-build-and-deploy
  resources:
    - name: source
      resourceRef:
        name: git-go-app
    - name: image
      resourceRef:
        name: image-go-app
