---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: kube-system
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = true

    [serversTransport]
      insecureSkipVerify = false

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.forwardedHeaders]
          trustedIPs = ["127.0.0.0/24", "10.42.0.0/16", "172.20.0.0/16", "59.12.195.87/32"]

      [entryPoints.https]
        address = ":443"
        [entryPoints.https.forwardedHeaders]
          trustedIPs = ["127.0.0.0/24", "10.42.0.0/16", "172.20.0.0/16", "59.12.195.87/32"]

      [entryPoints.traefik]
        address = ":8080"

      [entryPoints.metrics]
        address = ":8082"

    [api]
      debug = true
      dashboard = true
      insecure = false

    [providers]
      [providers.kubernetesCRD]
      [providers.file]
        filename = "/dynamic/dynamic_conf.toml"

    [metrics]
      [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
        entryPoint = "metrics"

    [ping]
      entryPoint = "http"

    [log]
      level = "Info"

    [accessLog]
      [accessLog.fields]
        defaultMode = "keep"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic
  namespace: kube-system
data:
  dynamic_conf.toml: |
    [http]
      [http.routers]
        [http.routers.traefik]
          entrypoint = ["traefik"]
          rule = "Host(`dev.brainest.ml`)"
          middlewares = ["secured"]
          service = "api@internal"

        [http.routers.https]
          entrypoint = ["https"]
          rule = "Host(`dev.brainest.ml`)"
          service = "api@internal"
          middlewares = ["secured"]
          [http.routers.https.tls]

        #[http.routers.metrics]
          #entrypoint = ["https"]
          #rule = "Host(`dev.brainest.ml`) && Path(`/metrics`)"
          #service = "metrics"
          #middlewares = ["redirect", "known-ips"]
          #[http.routers.metrics.tls]

        [http.routers.grafana]
          entrypoint = ["https"]
          rule = "Host(`dev.brainest.ml`) && PathPrefix(`/grafana`)"
          service = "grafana"
          ###########################################################
          # Since ipwhitelist is not working properly,
          # We are going to use basicAuth in Grafana
          # Please update its password manually after deploying it with helm:
          #
          # $ kubectl edit secret monitoring-grafana
          #
          middlewares = ["redirect", "known-ips", "prefix-grafana"]
          [http.routers.grafana.tls]

        [http.routers.alert]
          entrypoint = ["https"]
          rule = "Host(`dev.brainest.ml`) && PathPrefix(`/alertmanager`)"
          service = "alert"
          middlewares = ["secured", "prefix-alert"]
          [http.routers.alert.tls]


      [http.middlewares]
        [http.middlewares.secured.chain]
          middlewares = ["redirect", "known-ips", "adminAuth"]

        [http.middlewares.redirect.redirectScheme]
          scheme = "https"

        [http.middlewares.adminAuth.basicAuth]
          users = ["admin:$apr1$LfLN1FFq$wtEVm44GEwbYK7MMEGneX0"]

        [http.middlewares.prefix-grafana.stripPrefix]
          prefixes = ["/grafana"]

        [http.middlewares.prefix-alert.stripPrefix]
          prefixes = ["/alertmanager"]

      [http.middlewares.known-ips.ipWhiteList]
        ###########################################################
        # TODO: ipWhiteList is NOT working properly
        #
        ###########################################################
        sourceRange = ["127.0.0.1/24", "10.42.0.0/16", "172.20.0.0/16", "59.12.195.87/32"]
        #[http.middlewares.known-ips.ipWhiteList.ipStrategy] # looks NOT working in k3d
          #depth = 2

      #[http.services]
        #[http.services.metrics]
          #[[http.services.metrics.loadBalancer.servers]]
            #url = "http://localhost:8082"

        [http.services.grafana]
          [[http.services.grafana.loadBalancer.servers]]
            url = "http://monitoring-grafana.kube-system.svc.cluster.local"

        [http.services.alert]
          [[http.services.alert.loadBalancer.servers]]
            url = "http://monitoring-prometheus-oper-alertmanager.kube-system.svc.cluster.local:9093"

    [tls]
      [tls.options]
        [tls.options.default]
          minVersion = "VersionTLS12"
          sniStrict = true

      [[tls.certificates]]
        certFile = "/ssl/tls.crt"
        keyFile = "/ssl/tls.key"
        stores = ["default"]
