---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: kube-system
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = true

    [serversTransport]
      insecureSkipVerify = false

    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
      [entryPoints.traefik]
        address = ":8080"
      [entryPoints.metrics]
        address = ":8082"

    [api]
      debug = true
      dashboard = true
      insecure = false

    [providers]
    #[providers.kubernetesIngress] - disable after setup letsencrypt
      [providers.kubernetesCRD]
      [providers.file]
        filename = "/dynamic/dynamic_conf.toml"

    [metrics]
      [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
        entryPoint = "metrics"

    [ping]
      entryPoint = "http"

    [log]
      level = "Info"

    [accessLog]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic
  namespace: kube-system
data:
  dynamic_conf.toml: |
    [http]
      [http.routers]
        [http.routers.traefik]
          entrypoint = ["traefik"]
          rule = "Host(`dev.brainest.ml`)"
          middlewares = ["redirect"]
          service = "api@internal"

        [http.routers.metrics]
          entrypoint = ["https"]
          rule = "Host(`dev.brainest.ml`) && Path(`/metrics`)"
          service = "metrics"
          [http.routers.metrics.tls]

        [http.routers.grafana]
          entrypoint = ["https"]
          rule = "Host(`dev.brainest.ml`) && PathPrefix(`/grafana`)"
          service = "grafana"
          middlewares = ["prefix-grafana"]
          [http.routers.grafana.tls]

        [http.routers.https]
          entrypoint = ["https"]
          rule = "Host(`dev.brainest.ml`)"
          service = "api@internal"
          [http.routers.https.tls]

      [http.middlewares]
        [http.middlewares.redirect.redirectScheme]
          scheme = "https"
        [http.middlewares.adminAuth.basicAuth]
          users = ["admin:$apr1$M/jRzC2h$rYNFFONyKPHb5oMGB5t2u1"]
        [http.middlewares.prefix-grafana.stripPrefix]
          prefixes = ["/grafana"]

      [http.services]
        [http.services.metrics]
          [[http.services.metrics.loadBalancer.servers]]
            url = "http://localhost:8082"

        [http.services.grafana]
          [[http.services.grafana.loadBalancer.servers]]
            url = "http://monitoring-grafana.kube-system.svc.cluster.local"
    [tls]
      [tls.options]
        [tls.options.default]
          minVersion = "VersionTLS12"
          sniStrict = true

      [[tls.certificates]]
        certFile = "/ssl/tls.crt"
        keyFile = "/ssl/tls.key"
        stores = ["default"]
