---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: kube-system
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = true

    [serversTransport]
      insecureSkipVerify = true
      maxIdleConnsPerHost = 0

    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
      [entryPoints.traefik]
        address = ":8080"

    [api]
      dashboard = true
      insecure = true

    [providers]
      #providersThrottleDuration = "2s"
      #[providers.kubernetesIngress]
        #throttleDuration = "0s"

      [providers.kubernetesCRD]
        ingressClass = "traefik-private"

    [metrics]
      [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
        entryPoint = "metrics"

    [ping]
      entryPoint = "http"

    [log]
      level = "DEBUG"
---
