---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: kube-system
data:
  traefik.toml: |
    [global]
      checkNewVersion = true
      sendAnonymousUsage = true

    [serversTransport]
      insecureSkipVerify = false

    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
      [entryPoints.traefik]
        address = ":8080"

    [api]
      debug = true
      dashboard = true
      #insecure = true

    [providers]
    #[providers.kubernetesIngress]
      [providers.kubernetesCRD]
        namespaces = [ "kube-system" ]

    [metrics]
      [metrics.prometheus]
        buckets = [0.1,0.3,1.2,5.0]
        entryPoint = "metrics"

    [ping]
      entryPoint = "http"

    [log]
      level = "Debug"

    [certificatesResolvers]
      [certificatesResolvers.letsencrypt]
        [certificatesResolvers.letsencrypt.acme]
          email = "admin@brainest.ml"
          storage = "acme.json"
          # Uncomment to use Let's Encrypt's staging server, leave commented for prod
          caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
          [certificatesResolvers.letsencrypt.acme.httpChallenge]
            entryPoint = "http"
---
