---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    app: traefik
    #externalTrafficPolicy: Local
  ports:
  #- protocol: TCP
    #port: 80
    #targetPort: 80
    #name: http
  - protocol: TCP
    port: 443
    targetPort: 8080
    name: https
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: admin
  type: LoadBalancer
